name: Code Review Notification
on:
  pull_request:
    types: [opened, reopened, closed, edited, review_requested]
jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: bhavinmpanchal91@gmail.com
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Code Review Notification"
          to: bhavinmpanchal19@gmail.com  
          from: "bhavinmpanchal91@gmail.com"  
          body: |
            A pull request has been made to the repository.
            Repository: ${{ github.repository }}
            Pull Request: ${{ github.event.pull_request.html_url }}
            Author: ${{ github.event.pull_request.user.login }}
