name: Commit Notification
on:
  push:
    branches:
      - main
jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com  # Replace with your SMTP server address
          server_port: 587  # Replace with your SMTP server port
          username: bhavinmpanchal91@gmail.com
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Code Commit Notification"
          to: bhavinmpanchal19@gmail.com  # Replace with your email address
          from: "bhavinmpanchal91@gmail.com"  # Replace with the sender email address
          body: |
            A code commit has been made to the repository.
            Repository: ${{ github.repository }}
            Committer: ${{ github.actor }}
            Commit Message: ${{ github.event.head_commit.message }}
